# Site settings
title: Biodiversity
tag_text: Code for Victoria 2016 fellowship.
tag_sub_text: Team biodiversity.
description: "Code for Victoria 2016 fellowship working with the Department of Environment, Land, Water and Planning and Parks Victoria: Improving the collection and availability of biodiversity data."

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
# permalink: none
