# Site settings
title: Biodiversity
tag_text: Biodiversity
tag_sub_text: A Code for Australia, DELWP and Parks Victoria adventure.
description: "Code for Victoria 2016 fellowship working with the Department of Environment, Land, Water and Planning and Parks Victoria: Improving the collection and availability of biodiversity data."

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
# permalink: none
